version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: freeradius-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: radius
      MYSQL_USER: radius
      MYSQL_PASSWORD: radpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mariadb/create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
      - ./mariadb/setup_schema.sh:/docker-entrypoint-initdb.d/setup_schema.sh
    ports:
      - "3306:3306"
    restart: unless-stopped

  freeradius:
    build:
      context: ./freeradius
      dockerfile: Dockerfile
    container_name: freeradius-radius
    command: [ "freeradius", "-fX" ]
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    restart: unless-stopped
    depends_on:
      - mariadb

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: freeradius-server
    command: [ "apache2ctl", "-D", "FOREGROUND" ]
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - freeradius

  nginx:
    image: nginx:alpine
    container_name: freeradius-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    command: [ "nginx", "-g", "daemon off;" ]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  mariadb_data:
    driver: local
